"import random" 
"" 
"def roll_dice():" 
"    return random.randint(1, 6)" 
"" 
"print('Welcome to Snake and Ladder!')" 
"player_position = 0" 
"" 
"while player_position < 100:" 
"    input('Press Enter to roll the dice...')" 
"    dice = roll_dice()" 
"    player_position += dice" 
"    print(f'You rolled a {dice}. Current position: {player_position}')" 
"    if player_position >= 100:" 
"        print('Congratulations! You reached the finish line.')" 
"        break" 
